language: go

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"
  - "1.17.x"

before_install:
  - go get -t -v ./...

script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)